connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshops
  password: pass

development:
  <<: *connection
  database: netguru_workshops_development

test: &test
  <<: *connection
  database: netguru_workshops_test
