connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshops
  password: pass

development:
  <<: *connection
  database: netguru_workshops_development

test: &test
  <<: *connection
  database: netguru_workshops_test

production:
  adapter: posgresql
  encoding: unicode
  port: 5432
  database: d4gdjgcr56281n
  user: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

